# Generated by Django 5.1.6 on 2025-02-27 16:26

import book_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[book_app.models.validate_isbn_length]),
        ),
    ]
